---
- name: vmware_basic_linkedclone
  hosts: localhost
  gather_facts: false
      
  roles:
    - role: syncrou.manageiq-vmdb
    - role: vmware_basic_preprovision
      when: manageiq is defined

    - role: vmware_basic_vmname
    
    - role: vmware_linkedclone_provision

    - role: vmware_basic_postprovision
      when: vmware_created_vms is defined and manageiq is defined

- name: Perform tasks on instances
  hosts: vmware_hosts
  #become: true
  #gather_facts: false

  roles:
    - role: vmware_basic_runonce
