---
# vcenter parameters
hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
username: "{{ lookup('env', 'VMWARE_USER') }}"
password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
template: "{{ vcenter_template }}"
datacenter: "{{ vcenter_datacenter }}"
cluster: "{{ vcenter_cluster }}"
folder: "{{ vcenter_folder | default('/vm/') }}"
wait_for_ip_address: "{{ vcenter_wait_for_ip_address | default(true) }}"
validate_certs: "{{ vcenter_validate_certs | default(false) }}"

# vm guest parameters
vm_names: 
memory_mb: "{{ vm_memory_mb | default(1024) }}"
num_cpus: "{{ vm_num_cpus | default(1) }}"
notes: "{{ vm_notes | default('Provisioned by CloudForms via Ansible') }}"
vm_networks:
  - name: "{{ vm_vlan | default('VM Network 2') }}"
    type: static
    ip: "{{ vm_ip | default('10.9.62.40') }}"
    netmask: "{{ vm_netmask | default('255.255.255.224') }}"
    gateway: "{{ vm_gateway | default('10.9.62.33') }}"
    # mac: 
    domain: "{{ vm_domain | default('example.com') }}"
    dns_servers:
      - 10.9.62.86
      - 8.8.8.8


# disks:
#   - size_gb: "{{ vm_disk | default(10) }}"
#     type: thin
    # datastore: g73_datastore

# enable debugging
verbose: false